### ISSUE TITLE
Clighter won't start

### ISSUE THREAD

**Issue by sabastiaan** [bbchung/clighter8#1]
When I manually call StartClighter8 it returns "failed to init libclang" 

Vim version 2334 compiled with python, but without python 3.
let g:cligher8_libclang_path set to libclang-3.5 or libclang-3.8

**Comment by bbchung** [comment]
Is the given path absolute?, for example: 
let g:clighter8_libclang_path='/usr/lib/x86_64-linux-gnu/libclang-3.8.so.1'

**Comment by sabastiaan** [comment]
That path that you gave worked, 

I used to let set it to '/usr/lib/llvm-3.x/lib/libclang-3.x.so'

thanks!
