### ISSUE TITLE
Header file heuristics are dumb

### ISSUE THREAD

**Issue by petersohn** [bbchung/clighter8#10]
Header files are normally not present in the compilation database. It seems to me that if there is a `.cpp` file with the same name as the header, then Clighter8 uses the compilation arguments for that file. However, if there is no source corresponding to a header, then no arguments are inferred. It would be better if some other heuristic could be used, for example if there is another source in the same directory, then use the arguments for that.

**Comment by bbchung** [comment]
clighter8 uses smarter method, not the method you mentioned
