### ISSUE TITLE
Error: No such highlight group name clighter8Expr

### ISSUE THREAD

**Issue by matthiasvegh** [bbchung/clighter8#9]
Similarly to #5, the link for `clighter8Expr` is missing. Adding the link in syntax.vim fixes the issue for me.

    Error detected while processing function <lambda>332[1]..<SNR>118_on_get_hlt[10]<SNR>118_highlight:
    line   17:
    E28: No such highlight group name: clighter8Expr

**Comment by bbchung** [comment]
fixed
